version: '2'

services:
  app_server:
    build: dev-ops/docker/containers/php7
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir
      - .:/project
      - .:/var/www/shopware
    links:
      - app_mysql:mysql
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir
    ports:
      - "81:81"
      - "444:444"
    networks:
      sw_docker:
        ipv4_address: 10.100.112.46

  app_mysql:
    build: dev-ops/docker/containers/mysql
    volumes:
      - ./dev-ops/docker/_volumes/app-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      sw_docker:
        ipv4_address: 10.100.112.47
    ports:
      - "3307:3306"

  app_es:
    build: dev-ops/docker/containers/elastic-search
    volumes:
      - ./dev-ops/docker/containers/elastic-search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./dev-ops/docker/_volumes/app-es-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      TERM: xterm
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      sw_docker:
        ipv4_address: 10.100.112.48

  app_redis:
    build: dev-ops/docker/containers/redis
    volumes:
      - ./dev-ops/docker/_volumes/app-redisdata:/data
    networks:
      sw_docker:
        ipv4_address: 10.100.112.49

networks:
  sw_docker:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.100.112.0/24
        gateway: 10.100.112.1